packages:
  - "apps/*"

overrides:
  "@types/react": "$@types/react"
  "@types/react-dom": "$@types/react-dom"
  "undici@<7.29.1": "7.30.0"
  "fast-uri@<3.1.7": "3.1.8"
  "adm-zip@<0.6.1": "0.6.1"
  "brace-expansion@<1.1.18": "1.1.21"
  "minimatch@<3.1.4": "3.1.5"
  "smol-toml@<1.7.1": "1.9.0"
  "js-yaml@>=3.0.0 <3.15.2": "3.15.2"
  "prismjs@<1.30.0": "^1.30.0"
  "uuid@<11.1.1": "11.1.1"
