import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BootstrapClient from "@/components/BootstrapClient";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { sanityFetch, SanityLive } from "@/sanity/lib/live";
import { SITE_SETTINGS_QUERY } from "@/sanity/queries/siteSettings";
import "bootstrap-icons/font/bootstrap-icons.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/variables.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "DZTS Inmobiliaria",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data: siteSettings } = await sanityFetch({
    query: SITE_SETTINGS_QUERY,
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header
          logo={siteSettings?.logo}
          siteName={siteSettings?.siteName}
          navigation={siteSettings?.mainNavigation}
        />
        <main>{children}</main>
        <Footer
          logo={siteSettings?.logo}
          siteName={siteSettings?.siteName}
          copyrightText={siteSettings?.copyrightText}
          footerLinks={siteSettings?.footerLinks}
          certificationLogos={siteSettings?.certificationLogos}
          socialLinks={siteSettings?.socialLinks}
        />
        <BootstrapClient />
        <SanityLive />
      </body>
    </html>
  );
}
