/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PropertyTypeCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "propertyTypeCategory";
};

export type CityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "city";
};

export type Property = {
  _id: string;
  _type: "property";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  title?: string;
  subtitle?: string;
  publishedAt?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  operationType?: "venta" | "alquiler";
  propertyType?: PropertyTypeCategoryReference;
  address?: string;
  neighborhood?: string;
  city?: CityReference;
  rooms?: number;
  bathrooms?: number;
  garages?: number;
  size?: number;
  price?: number;
  currency?: "USD" | "ARS";
  featured?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type PropertyTypeCategory = {
  _id: string;
  _type: "propertyTypeCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type City = {
  _id: string;
  _type: "city";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mainNavigation?: Array<{
    label?: string;
    linkType?: "internal" | "external" | "action";
    internalPath?: string;
    externalUrl?: string;
    actionId?: string;
    _type: "navItem";
    _key: string;
  }>;
  phone?: string;
  email?: string;
  address?: string;
  whatsappNumber?: string;
  socialLinks?: Array<{
    platform?: "facebook" | "instagram" | "twitter" | "linkedin" | "youtube";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  copyrightText?: string;
  footerLinks?: Array<{
    label?: string;
    url?: string;
    _type: "footerLink";
    _key: string;
  }>;
  certificationLogos?: Array<{
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt?: string;
    title?: string;
    url?: string;
    _type: "certificationLogo";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | PropertyTypeCategoryReference
  | CityReference
  | Property
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | PropertyTypeCategory
  | City
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: ../frontend/src/app/page.tsx
// Variable: CITIES_QUERY
// Query: *[_type == "city"] | order(name asc) { name, "slug": slug.current }
export type CITIES_QUERY_RESULT = Array<{
  name: string | null;
  slug: string | null;
}>;

// Source: ../frontend/src/app/page.tsx
// Variable: PROPERTY_TYPES_QUERY
// Query: *[_type == "propertyTypeCategory"] | order(name asc) { name, "slug": slug.current }
export type PROPERTY_TYPES_QUERY_RESULT = Array<{
  name: string | null;
  slug: string | null;
}>;

// Source: ../frontend/src/app/page.tsx
// Variable: ROOM_COUNTS_QUERY
// Query: array::unique(*[_type == "property" && defined(rooms)].rooms) | order(@ asc)
export type ROOM_COUNTS_QUERY_RESULT = Array<number>;

// Source: ../frontend/src/app/propiedades/[slug]/page.tsx
// Variable: PROPERTY_QUERY
// Query: *[_type == "property" && slug.current == $slug][0]   {    title,    subtitle,    address,    description,    price,    "propertyType": propertyType->name,    operationType,    currency,    "city": city->name,    "images": images[]  }
export type PROPERTY_QUERY_RESULT = {
  title: string | null;
  subtitle: string | null;
  address: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  price: number | null;
  propertyType: string | null;
  operationType: "alquiler" | "venta" | null;
  currency: "ARS" | "USD" | null;
  city: string | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
} | null;

// Source: ../frontend/src/components/FeaturedProperties.tsx
// Variable: FEATURED_QUERY
// Query: *  [_type == "property" && featured == true]  | order(publishedAt desc)[0...6]  {    _id,    title,    "slug": slug.current,    subtitle,    price,    currency,    operationType,    rooms,    "city": city->name,    "image": images[0]  }
export type FEATURED_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  price: number | null;
  currency: "ARS" | "USD" | null;
  operationType: "alquiler" | "venta" | null;
  rooms: number | null;
  city: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | null;
}>;

// Source: ../frontend/src/sanity/queries/siteSettings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    siteName,    logo {      asset->{        _id,        url,        metadata { lqip, dimensions }      },      alt    },    favicon {      asset->{        _id,        url      }    },    mainNavigation[] {      _key,      label,      linkType,      internalPath,      externalUrl,      actionId    },    phone,    email,    address,    whatsappNumber,    socialLinks[] {      _key,      platform,      url    },    copyrightText,    footerLinks[] {      _key,      label,      url    },    certificationLogos[] {      _key,      image {        asset->{          _id,          url,          metadata { lqip, dimensions }        }      },      alt,      title,      url    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  siteName: string | null;
  logo: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  favicon: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  mainNavigation: Array<{
    _key: string;
    label: string | null;
    linkType: "action" | "external" | "internal" | null;
    internalPath: string | null;
    externalUrl: string | null;
    actionId: string | null;
  }> | null;
  phone: string | null;
  email: string | null;
  address: string | null;
  whatsappNumber: string | null;
  socialLinks: Array<{
    _key: string;
    platform:
      | "facebook"
      | "instagram"
      | "linkedin"
      | "twitter"
      | "youtube"
      | null;
    url: string | null;
  }> | null;
  copyrightText: string | null;
  footerLinks: Array<{
    _key: string;
    label: string | null;
    url: string | null;
  }> | null;
  certificationLogos: Array<{
    _key: string;
    image: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    title: string | null;
    url: string | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "city"] | order(name asc) { name, "slug": slug.current }\n': CITIES_QUERY_RESULT;
    '\n  *[_type == "propertyTypeCategory"] | order(name asc) { name, "slug": slug.current }\n': PROPERTY_TYPES_QUERY_RESULT;
    '\n  array::unique(*[_type == "property" && defined(rooms)].rooms) | order(@ asc)\n': ROOM_COUNTS_QUERY_RESULT;
    '\n  *[_type == "property" && slug.current == $slug][0] \n  {\n    title,\n    subtitle,\n    address,\n    description,\n    price,\n    "propertyType": propertyType->name,\n    operationType,\n    currency,\n    "city": city->name,\n    "images": images[]\n  }\n': PROPERTY_QUERY_RESULT;
    '*\n  [_type == "property" && featured == true]\n  | order(publishedAt desc)[0...6]\n  {\n    _id,\n    title,\n    "slug": slug.current,\n    subtitle,\n    price,\n    currency,\n    operationType,\n    rooms,\n    "city": city->name,\n    "image": images[0]\n  }': FEATURED_QUERY_RESULT;
    '\n  *[_type == "siteSettings"][0] {\n    siteName,\n    logo {\n      asset->{\n        _id,\n        url,\n        metadata { lqip, dimensions }\n      },\n      alt\n    },\n    favicon {\n      asset->{\n        _id,\n        url\n      }\n    },\n    mainNavigation[] {\n      _key,\n      label,\n      linkType,\n      internalPath,\n      externalUrl,\n      actionId\n    },\n    phone,\n    email,\n    address,\n    whatsappNumber,\n    socialLinks[] {\n      _key,\n      platform,\n      url\n    },\n    copyrightText,\n    footerLinks[] {\n      _key,\n      label,\n      url\n    },\n    certificationLogos[] {\n      _key,\n      image {\n        asset->{\n          _id,\n          url,\n          metadata { lqip, dimensions }\n        }\n      },\n      alt,\n      title,\n      url\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
